#!/bin/zsh

set -u

[[ -n ${FAKE_CURL_LOG:-} ]] && print -r -- "${(j: :)@}" >> "$FAKE_CURL_LOG"
[[ ${FAKE_HEALTH_STATUS:-failure} == success ]] || exit 22
typeset body=${FAKE_HEALTH_BODY:-} code=${FAKE_HEALTH_CODE:-200}
[[ -n $body ]] || body='{"status":"ok"}'
print -r -- "$body"
print -r -- "$code"
