#!/bin/zsh

set -u

[[ -n ${FAKE_CURL_LOG:-} ]] && print -r -- "${(j: :)@}" >> "$FAKE_CURL_LOG"
[[ ${FAKE_HEALTH_STATUS:-failure} == success ]] || exit 22
typeset body=${FAKE_HEALTH_BODY:-}
[[ -n $body ]] || body='{"status":"ok"}'
print -r -- "$body"
