#!/bin/zsh

set -u

print -r -- "${(j: :)@}" >> "${FAKE_TUNNEL_LOG:?}"
if [[ -n ${FAKE_TUNNEL_ENV_LOG:-} ]]; then
  print -r -- "CONTROL_PLANE_API_KEY=${CONTROL_PLANE_API_KEY:-} CONTROL_PLANE_API_KEY_2=${CONTROL_PLANE_API_KEY_2:-} CONTROL_PLANE_API_KEY_AGENT=${CONTROL_PLANE_API_KEY_AGENT:-} CONTROL_PLANE_API_KEY_ACCT2=${CONTROL_PLANE_API_KEY_ACCT2:-}" >> "$FAKE_TUNNEL_ENV_LOG"
fi
[[ ${FAKE_TUNNEL_EXIT:-0} == 1 ]] && exit 1
mkdir -p "${FAKE_PROCESS_DIR:?}"
print -r -- "$0 ${(j: :)@}" > "$FAKE_PROCESS_DIR/$$.command"

typeset pid_file="" health_file=""
typeset -i i=1
while (( i <= $# )); do
  case ${@[i]} in
    --pid.file)
      (( i++ ))
      pid_file=${@[i]}
      ;;
    --health.url-file)
      (( i++ ))
      health_file=${@[i]}
      ;;
  esac
  (( i++ ))
done

[[ -n $pid_file ]] && print -r -- "$$" > "$pid_file"
[[ ${FAKE_TUNNEL_HEALTH:-1} == 1 && -n $health_file ]] && print -r -- "http://127.0.0.1:54321" > "$health_file"

trap 'rm -f "$FAKE_PROCESS_DIR/$$.command"; exit 0' TERM INT
while true; do
  sleep 1
done
